# Generated by Django 5.1.2 on 2024-10-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_api_key_user_claude_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="claude_tokens",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="openai_tokens",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
