
# Generated by Django 5.1.2 on 2024-10-18 13:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ("users", "0003_remove_user_name_alter_user_gender"),

    ]

    operations = [
        migrations.AlterField(

            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=150),

        ),
    ]
