# Generated by Django 5.1.2 on 2024-10-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ai_message',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_message',
            field=models.TextField(default='', null=True),
        ),
    ]
