# Generated by Django 5.1.2 on 2024-10-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gptmessages", "0002_alter_message_ai_message_alter_message_user_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="ai_message",
        ),
        migrations.RemoveField(
            model_name="message",
            name="user_message",
        ),
        migrations.AddField(
            model_name="message",
            name="message_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="message_role",
            field=models.CharField(
                blank=True,
                choices=[("human", "human"), ("ai", "ai")],
                max_length=10,
                null=True,
            ),
        ),
    ]
