# Generated by Django 5.1.2 on 2024-10-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gptmessages", "0002_message_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="owner",
        ),
    ]
