# Generated by Django 5.1.2 on 2024-10-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gptmessages", "0003_remove_message_ai_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gpt-4o-mini-2024-07-18", "gpt-4o-mini-2024-07-18"),
                    ("gpt-4o-2024-08-06", "gpt-4o-2024-08-06"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="token",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
