# Generated by Django 5.1.2 on 2024-10-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gptmessages", "0004_message_model_message_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
