# Generated by Django 5.1.2 on 2024-10-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gptconversations", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="name",
            new_name="title",
        ),
    ]
