# Generated by Django 5.1.2 on 2024-10-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gptconversations", "0003_rename_name_conversation_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
