# Generated by Django 5.1.2 on 2024-10-22 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gptconversations", "0006_alter_conversation_pdf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="pdf",
            new_name="file",
        ),
    ]
