# Generated by Django 5.1.2 on 2024-10-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gptconversations", "0007_rename_pdf_conversation_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="file",
            field=models.URLField(blank=True, null=True),
        ),
    ]
