# Generated by Django 5.1.2 on 2024-10-22 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gptconversations", "0009_conversation_file_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="file",
            new_name="file_url",
        ),
    ]
